# Generated by Django 4.2.16 on 2024-09-09 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_sequence_delete_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='sequence',
            name='additional_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='sequence',
            name='aa_sequence',
            field=models.CharField(max_length=35000),
        ),
        migrations.AlterField(
            model_name='sequence',
            name='individual',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='sequence',
            name='protein',
            field=models.CharField(max_length=25),
        ),
    ]
