# Generated by Django 4.2.16 on 2024-09-09 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_sequence_additional_data_alter_sequence_aa_sequence_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sequence',
            old_name='additional_data',
            new_name='variants',
        ),
    ]
