# Generated by Django 4.2.16 on 2024-09-09 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rename_additional_data_sequence_variants'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sequence',
            old_name='protein',
            new_name='Accession',
        ),
        migrations.RenameField(
            model_name='sequence',
            old_name='individual',
            new_name='Individual',
        ),
        migrations.RenameField(
            model_name='sequence',
            old_name='aa_sequence',
            new_name='Sequence',
        ),
        migrations.RemoveField(
            model_name='sequence',
            name='variants',
        ),
        migrations.AddField(
            model_name='sequence',
            name='Variants',
            field=models.JSONField(default=dict),
        ),
    ]
