# Generated by Django 4.2.16 on 2024-09-15 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_rename_protein_sequence_accession_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sequence',
            name='Nucleotide_Variants',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='sequence',
            name='Variants',
            field=models.JSONField(default=list),
        ),
    ]
