# Generated by Django 4.2.16 on 2024-09-16 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_sequence_nucleotide_variants_alter_sequence_variants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sequence',
            name='Nucleotide_Variants',
        ),
        migrations.AlterField(
            model_name='sequence',
            name='Variants',
            field=models.JSONField(default=dict),
        ),
    ]
