# Generated by Django 4.2.16 on 2024-09-18 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_remove_sequence_nucleotide_variants_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sequence',
            name='Individual',
        ),
        migrations.RemoveField(
            model_name='sequence',
            name='Sequence',
        ),
    ]
