# Generated by Django 4.2.16 on 2024-09-18 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_sequence_cohorts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sequence',
            name='Cohorts',
            field=models.JSONField(default=list),
        ),
    ]
