# Generated by Django 4.2.16 on 2024-09-25 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_sequence_cohorts'),
    ]

    operations = [
        migrations.AddField(
            model_name='sequence',
            name='Sequence',
            field=models.CharField(default=str, max_length=35000),
        ),
    ]
