# Generated by Django 4.2.16 on 2024-11-13 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_sequence_sequence'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Individual', models.CharField(max_length=3)),
                ('Age', models.IntegerField()),
                ('Disease', models.BinaryField()),
                ('Sex', models.BinaryField()),
                ('Drug', models.BinaryField()),
                ('BMI', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Sequence_and_CHalf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Accession', models.CharField(max_length=25)),
                ('Variants', models.JSONField(default=dict)),
                ('Sequence', models.CharField(default=str, max_length=35000)),
            ],
        ),
        migrations.DeleteModel(
            name='Sequence',
        ),
    ]
