# Generated by Django 4.2.16 on 2024-11-14 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_metadata_sequence_and_chalf_delete_sequence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadata',
            name='Disease',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='Drug',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='Sex',
            field=models.BooleanField(),
        ),
    ]
