# Generated by Django 4.2.16 on 2024-11-18 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_alter_metadata_disease_alter_metadata_drug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sequence_and_chalf',
            name='CHalf',
            field=models.JSONField(default=dict),
        ),
    ]
