# Generated by Django 4.2.16 on 2024-11-18 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_sequence_and_chalf_chalf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sequence_and_chalf',
            name='Accession',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
