# Generated by Django 4.2.16 on 2024-11-19 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_alter_sequence_and_chalf_accession'),
    ]

    operations = [
        migrations.CreateModel(
            name='CHalf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Accession', models.CharField(max_length=25, unique=True)),
                ('CHalf', models.JSONField(default=dict)),
            ],
        ),
        migrations.RemoveField(
            model_name='sequence_and_chalf',
            name='CHalf',
        ),
    ]
