# Generated by Django 4.2.16 on 2024-11-19 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_chalf_remove_sequence_and_chalf_chalf'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sequence_and_CHalf',
            new_name='Sequence',
        ),
    ]
